### ISSUE TITLE
Duplicate ff_inverse symbols in xcode

### ISSUE THREAD

**Issue by streetgainer** [ciphor/ffmpeg4ios#3]
Error rec'vd during xcode's build/linking phase:

> > > ld: duplicate symbol _ff_inverse in /Users/PatsMac/Developer/Platforms/IPhoneUniversal.platform/libavcodec.a(inverse.o) and /Users/PatsMac/Developer/Platforms/IPhoneUniversal.platform/libavutil.a(inverse.o) for architecture armv7
> > > collect2: ld returned 1 exit status
> > > Command /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc-4.2 failed with exit code 1

I can't figure out away around this, any ideas?

Thanks
Pat

**Comment by mikeyward** [comment]
Did you ever find a workaround?

**Comment by streetgainer** [comment]
Yes, had to role back the ffmpeg version to 0.6.5, anything newer will encounter symbol collision problems in xcode.
